name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-macos-arm64:
    name: Build macOS arm64
    runs-on: macos-15
    strategy:
      matrix:
        architecture: ['arm64']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          brew install autoconf
          brew install automake
          brew install wget
          wget https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0.tar.gz
          tar -zxf aria2-1.37.0.tar.gz
          cd aria2-1.37.0
          cp ../makerelease-osx-v2.mk ./
          mkdir build-release
          cd build-release
          ln -s ../makerelease-osx-v2.mk Makefile
          make ARCH=${{ matrix.architecture }}
          cd aria2-def/bin
          tar -zcf aria2c-macos-${{ matrix.architecture }}.tar.gz aria2c
          cp aria2c-macos-${{ matrix.architecture }}.tar.gz ${{ github.workspace }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aria2c-macos-${{ matrix.architecture }}
          path: aria2c-macos-${{ matrix.architecture }}.tar.gz
          
  build-macos-x86_64:
    name: Build macOS x86_64
    runs-on: macos-15-intel
    strategy:
      matrix:
        architecture: ['x86_64']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          brew install autoconf
          brew install automake
          brew install wget
          wget https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0.tar.gz
          tar -zxf aria2-1.37.0.tar.gz
          cd aria2-1.37.0
          cp ../makerelease-osx-v2.mk ./
          mkdir build-release
          cd build-release
          ln -s ../makerelease-osx-v2.mk Makefile
          make ARCH=${{ matrix.architecture }}
          cd aria2-def/bin
          tar -zcf aria2c-macos-${{ matrix.architecture }}.tar.gz aria2c
          cp aria2c-macos-${{ matrix.architecture }}.tar.gz ${{ github.workspace }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aria2c-macos-${{ matrix.architecture }}
          path: aria2c-macos-${{ matrix.architecture }}.tar.gz

